-- mebody Ver2 questions migration + seed
-- 실행 위치: Supabase SQL Editor

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_number INT NOT NULL,
  axis TEXT NOT NULL,
  question_text TEXT NOT NULL,
  option_1 TEXT NOT NULL,
  option_2 TEXT NOT NULL,
  option_3 TEXT NOT NULL,
  weight_a INT NOT NULL DEFAULT 1,
  weight_b INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_number INT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS axis TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_text TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_1 TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_2 TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_3 TEXT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS weight_a INT DEFAULT 1;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS weight_b INT DEFAULT 1;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS questions_question_number_key ON questions (question_number);

INSERT INTO questions (
  question_number, axis, question_text, option_1, option_2, option_3, weight_a, weight_b
) VALUES
  (1, 'neck', '10초 휴대폰 보기(즉시)', '① 턱이 화면 쪽으로 나가고, 목이 많이 숙여진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 휴대폰을 눈높이 쪽으로 올려, 목이 크게 숙지 않는다', 2, 2),
  (2, 'neck', '벽 정렬: 뒤통수 닿음(즉시)', '① 뒤통수가 벽에 잘 안 닿는다(턱이 앞으로/위로)', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 뒤통수·등·골반이 비교적 자연스럽게 같이 닿는다', 2, 2),
  (3, 'neck', '옆모습 사진: 귀-어깨 선(즉시)', '① 귀가 어깨보다 확실히 앞으로 나와 있다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 귀가 어깨와 거의 같은 선이거나 약간 뒤에 있다', 3, 3),
  (4, 'neck', '의자에 앉아 엉덩이 깊게, 등을 등받이에 붙여. 그 상태에서 화면을 정면으로 보면 고개가 앞으로 나가나요?', '① 등을 붙여도 턱/얼굴이 앞으로 나가야 보기 편하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 등을 붙인 상태에서도 턱을 앞으로 내밀지 않고 보기 편하다', 3, 3),
  (5, 'neck', '턱 당기기 10초(즉시)', '① 3~5초도 힘들고, 앞목/턱밑이 금방 힘들어진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 10초가 비교적 편하고, 목이 길게 유지된다', 3, 3),
  (6, 'neck', '컴퓨터/휴대폰 30분 후 먼저 느껴지는 것(경험, "피로감")', '① 뒷목/목 위쪽이 먼저 피로해진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 목보다는 등/허리가 먼저 피로해진다', 1, 1),
  (7, 'neck', '자기 인식', '① 나는 거북목/앞으로 쏠림에 가깝다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 나는 목이 많이 나가 있진 않은 편이다', 1, 1),
  (8, 'shoulder', '거울 앞 힘 빼고 섰을 때(즉시)', '① 오른쪽 어깨가 더 올라가 보인다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 어깨가 더 올라가 보인다', 3, 3),
  (9, 'shoulder', '사진으로 목-어깨 라인 길이(즉시)', '① 오른쪽 귀밑~어깨 라인이 더 짧아 보인다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 라인이 더 짧아 보인다', 2, 2),
  (10, 'shoulder', '가방/옷 끈이 자주 흘러내리는 쪽(최근 7일)', '① 오른쪽에서 더 자주 흘러내린다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽에서 더 자주 흘러내린다', 1, 1),
  (11, 'shoulder', '양팔 툭 떨어뜨린 손끝 높이(즉시)', '① 오른쪽 손끝이 더 위에 있다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 손끝이 더 위에 있다', 1, 1),
  (12, 'shoulder', '옆으로 누워 쉬는 쪽(습관)', '① 오른쪽으로 더 자주 눕는다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽으로 더 자주 눕는다', 1, 1),
  (13, 'shoulder', '팔 옆으로 들어 90도(즉시)', '① 오른쪽 어깨가 더 으쓱 올라가 보인다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 어깨가 더 으쓱 올라가 보인다', 3, 3),
  (14, 'shoulder', '으쓱 3번: 더 먼저/더 크게 올라가는 쪽(즉시)', '① 오른쪽', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽', 3, 3),
  (15, 'shoulder', '팔짱: 위로 올라오는 팔', '① 오른팔', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼팔', 1, 1),
  (16, 'shoulder', '목 옆~어깨선 스트레치 시 더 "빡빡한" 쪽', '① 오른쪽이 더 빡빡하게 느껴진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽이 더 빡빡하게 느껴진다', 1, 1),
  (17, 'shoulder', '무의식적으로 힘이 더 들어가는 어깨', '① 오른쪽 어깨에 힘이 더 들어간다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 어깨에 힘이 더 들어간다', 1, 1),
  (18, 'pelvis', '거울 정면: 골반 "앞으로 나온 쪽"', '① 오른쪽 골반(허리선)이 더 앞으로 나와 보인다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 골반(허리선)이 더 앞으로 나와 보인다', 5, 5),
  (19, 'pelvis', '바지/벨트 중앙선 돌아감', '① 오른쪽으로 더 자주 돌아간다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽으로 더 자주 돌아간다', 1, 1),
  (20, 'pelvis', '벽 기대기: 엉덩이 먼저 닿는 쪽', '① 오른쪽 엉덩이가 먼저/더 크게 닿는다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 엉덩이가 먼저/더 크게 닿는다', 2, 2),
  (21, 'pelvis', '딱딱한 의자: 좌골(엉덩이뼈) 압력', '① 오른쪽이 더 강하게 닿는다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽이 더 강하게 닿는다', 2, 2),
  (22, 'pelvis', '"짝다리/체중 싣기" 더 편한 다리(습관)', '① 오른쪽 다리에 체중 싣는 게 더 편하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 다리에 체중 싣는 게 더 편하다', 1, 1),
  (23, 'pelvis', '앉아서 다리 꼬기: "더 편한" 위쪽 다리(습관)', '① 오른다리가 위로 오는 게 더 편하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼다리가 위로 오는 게 더 편하다', 1, 1),
  (24, 'pelvis', '바로 누워 힘 빼기: 발끝이 더 바깥으로 향하는 쪽', '① 오른발 끝이 더 바깥으로 돌아가 있다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼발 끝이 더 바깥으로 돌아가 있다', 1, 1),
  (25, 'pelvis', '눈 감고 제자리 걸음 10초 후 방향', '① 몸이 오른쪽으로 더 돌아가 있다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 몸이 왼쪽으로 더 돌아가 있다', 2, 2),
  (26, 'pelvis', '스쿼트(가볍게): 무릎이 더 바깥으로 벌어지는 쪽', '① 오른쪽 무릎이 더 바깥으로 벌어진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽 무릎이 더 바깥으로 벌어진다', 1, 1),
  (27, 'pelvis', '서 있을 때 "틀어진 느낌" 방향', '① 오른쪽으로 틀어진 느낌이 더 가깝다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 왼쪽으로 틀어진 느낌이 더 가깝다', 1, 1),
  (28, 'flexibility', '무릎 펴고 상체 숙이기', '① 손끝이 무릎 근처', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 손끝이 발등/바닥 가까이', 2, 2),
  (29, 'flexibility', '완전 쪼그려 앉기(즉시, 5초)', '① 거의 불가/뒤꿈치가 많이 뜬다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 편하게 5초 가능', 2, 2),
  (30, 'flexibility', '발목 유연성: 무릎-벽 테스트(10cm)
세팅: 벽 앞에서 엄지발가락 10cm, 뒤꿈치 안 들고 무릎을 벽에 닿게', '① 10cm는 어렵다(뒤꿈치 들림/안 닿음)', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 10cm도 비교적 쉽게 닿는다', 4, 4),
  (31, 'flexibility', '런지 자세(무릎 바닥)로 앞쪽 사타구니 늘림(즉시)
세팅: 한쪽 무릎을 바닥에 대고(매트/수건), 반대발은 앞에. 골반을 살짝 말고 상체는 곧게.', '① 사타구니 앞이 강하게 뻣뻣하고 자세가 유지가 어렵다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 편하게 늘어난다', 2, 2),
  (32, 'flexibility', '허벅지 앞 늘리기(서서 발목 잡기, 즉시)', '① 발꿈치가 엉덩이 쪽으로 거의 안 오고 강하게 뻣뻣하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 잘 오고 편하다', 2, 2),
  (33, 'flexibility', '발끝 힘 빼고, 허리 편 채 "엉덩이 뒤로 빼며" 숙이기
세팅: 발바닥 전체 바닥, 발끝 일부러 들지 말고 힘만 빼기, 무릎은 쭉(잠그진 말고), 허리는 편하게', '① 뒤허벅지/엉덩이 아래가 빨리 강하게 뻣뻣해져 많이 못 숙인다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 잘 숙여지고 뻣뻣함이 심하지 않다', 4, 4),
  (34, 'flexibility', '누워서 한쪽 무릎 가슴 쪽(즉시)', '① 무릎이 잘 안 올라오고 뒤쪽 엉덩이 / 엉덩이-허벅지 경계가 뻣뻣하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 잘 올라오고 편하다', 2, 2),
  (35, 'flexibility', '나비자세(고관절/내전근)', '① 무릎이 많이 뜨고 불편해서 자세 유지가 어렵다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 무릎이 비교적 잘 내려가고 편하다', 1, 1),
  (36, 'flexibility', '힙힌지(허리 편 상태로 상체 숙이기) 5회(즉시)
설명: "허리는 편하게 유지" + "엉덩이를 뒤로 빼며" 상체를 숙였다가 올라오기', '① 허리가 먼저 둥글게 말리거나 허리로 접히는 느낌이 강하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 허리 말림이 적고, 엉덩이 접힘(고관절)로 숙이는 느낌이 난다', 2, 2),
  (37, 'flexibility', '의자 앉아 ''4자'' 자세
세팅: 의자에 앉아 오른발목을 왼쪽 무릎 위에 올려 ''4'' 모양(양쪽 다 해봄)', '① 무릎이 많이 떠서 자세가 불편하거나 뻣뻣하다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 편하고 무릎이 잘 내려간다', 1, 1),
  (38, 'flexibility', '벽 짚고 뒤꿈치 들기 10회
설명: 벽을 가볍게 짚고, 뒤꿈치를 천천히 올렸다 내리기 10회(반동X)', '① 10회가 어렵고 종아리가 빨리 뻣뻣해진다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 10회가 비교적 쉽고 뻣뻣함이 심하지 않다', 2, 2),
  (39, 'flexibility', '계단/스텝 없이 가능한 "발목 앞쪽 접힘" 체크(즉시)
설명: 벽 앞에서 한 발을 앞으로 두고(앞발), 무릎을 천천히 앞으로 보내 벽에 닿게(뒤꿈치 안 들기) — 5회', '① 뒤꿈치가 들리거나 무릎이 앞으로 잘 못 간다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 비교적 잘 된다(뒤꿈치 유지)', 3, 3),
  (40, 'flexibility', '운동/활동 전 "몸 풀기" 필요도', '① 스트레칭이나 몸을 풀어야 운동/활동할 때 움직임이 잘 나온다', '② 잘 모르겠다 / 상황에 따라 다르다', '③ 몸을 안 풀어도 운동/활동할 때 움직임이 잘 나온다', 1, 1)
ON CONFLICT (question_number) DO UPDATE SET
  axis = EXCLUDED.axis,
  question_text = EXCLUDED.question_text,
  option_1 = EXCLUDED.option_1,
  option_2 = EXCLUDED.option_2,
  option_3 = EXCLUDED.option_3,
  weight_a = EXCLUDED.weight_a,
  weight_b = EXCLUDED.weight_b,
  updated_at = now();

ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'questions' AND policyname = 'questions read'
  ) THEN
    CREATE POLICY "questions read" ON questions FOR SELECT USING (true);
  END IF;
END $$;
