-- MEBODY V1 schema: 32 questions + choice score mappings
ALTER TABLE public.questions
  ADD COLUMN IF NOT EXISTS question_set text DEFAULT 'v3_full',
  ADD COLUMN IF NOT EXISTS media_type text,
  ADD COLUMN IF NOT EXISTS media_url text,
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS part text,
  ADD COLUMN IF NOT EXISTS instruction text,
  ADD COLUMN IF NOT EXISTS guide_text text,
  ADD COLUMN IF NOT EXISTS axis_anchor text,
  ADD COLUMN IF NOT EXISTS axis_priority integer;

CREATE INDEX IF NOT EXISTS questions_set_active_idx
  ON public.questions (question_set, is_active, sort_order);

CREATE UNIQUE INDEX IF NOT EXISTS questions_code_set_uidx
  ON public.questions (question_code, question_set);

CREATE TABLE IF NOT EXISTS public.question_choice_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_set text NOT NULL DEFAULT 'mebody_v1_32',
  question_code text NOT NULL,
  choice text NOT NULL CHECK (choice = ANY (ARRAY['①','②','③'])),
  choice_summary text,
  axis text,
  direction text,
  axis_weight integer NOT NULL DEFAULT 0,
  axis_anchor text,
  axis_priority integer,
  score_recovery integer NOT NULL DEFAULT 0,
  score_strength integer NOT NULL DEFAULT 0,
  score_mobility integer NOT NULL DEFAULT 0,
  score_balance integer NOT NULL DEFAULT 0,
  identity_anchor text,
  aux_tag text,
  display_order integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (question_set, question_code, choice)
);

CREATE INDEX IF NOT EXISTS question_choice_scores_set_idx
  ON public.question_choice_scores (question_set, question_code);

ALTER TABLE public.questionnaire_responses
  ADD COLUMN IF NOT EXISTS primary_identity text,
  ADD COLUMN IF NOT EXISTS scoring_meta jsonb DEFAULT '{}'::jsonb;

ALTER TABLE public.question_choice_scores ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename='question_choice_scores' AND policyname='choice_scores_public_read'
  ) THEN
    CREATE POLICY choice_scores_public_read ON public.question_choice_scores
      FOR SELECT TO anon, authenticated USING (true);
  END IF;
END $$;

COMMENT ON TABLE public.questions IS
  'Questionnaire UI source (32 rows for mebody_v1_32): question_text, options, instruction, guide_text, media. DO NOT DROP — app fetchQuestions() reads this table.';
COMMENT ON COLUMN public.questions.question_set IS 'mebody_v1_32 | sample_subjective_v1 | v3_full';
COMMENT ON TABLE public.question_choice_scores IS
  'Per-choice scoring map (96 rows = 32×3): axis/identity scores. Complements questions; does not replace it. App runtime currently uses bundled v1ScoreMapping.ts (same source).';
