INSERT INTO public.question_choice_scores (
  question_set, question_code, choice, choice_summary,
  axis, direction, axis_weight, axis_anchor, axis_priority,
  score_recovery, score_strength, score_mobility, score_balance,
  identity_anchor, aux_tag, display_order
) VALUES
('mebody_v1_32', 'A1', '①', '일주일에 3회 이상 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 1),
('mebody_v1_32', 'A1', '②', '일주일에 1~2회 정도 한다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 0, '근력 보완형:Supporting', NULL, 1),
('mebody_v1_32', 'A1', '③', '거의 하지 않는다', NULL, NULL, 0, 'None', NULL, 0, 2, 0, 0, '근력 보완형:Supporting', NULL, 1),
('mebody_v1_32', 'A2', '①', '자주 그렇다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '수면 후 회복감 낮음', 2),
('mebody_v1_32', 'A2', '②', '가끔 그렇다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', '수면 후 회복감 변동', 2),
('mebody_v1_32', 'A2', '③', '거의 그렇지 않다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 2),
('mebody_v1_32', 'A3', '①', '몸이 무겁고 뻣뻣해서 바로 움직이기 어렵다', 'flexibility', 'S', 1, 'Supporting', 3, 2, 0, 1, 0, '회복 우선형:Supporting / 움직임 제한형:Supporting', NULL, 3),
('mebody_v1_32', 'A3', '②', '상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Supporting', NULL, 3),
('mebody_v1_32', 'A3', '③', '비교적 바로 편하게 움직일 수 있다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 3),
('mebody_v1_32', 'A4', '①', '다음 날까지 몸이 무겁고 피로가 오래간다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '활동 후 회복 지연', 4),
('mebody_v1_32', 'A4', '②', '활동량이나 상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', NULL, 4),
('mebody_v1_32', 'A4', '③', '비교적 잘 회복되는 편이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 4),
('mebody_v1_32', 'A5', '①', '몸의 긴장이 오래 남는 편이다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '긴장 후 이완 지연', 5),
('mebody_v1_32', 'A5', '②', '상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', NULL, 5),
('mebody_v1_32', 'A5', '③', '비교적 쉽게 편안해지는 편이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 5),
('mebody_v1_32', 'A6', '①', '손잡이를 자주 잡거나 불안해서 조심스럽게 내려간다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 3, '근력 보완형:Secondary / 밸런스 개선형:Primary', '계단 불안/손잡이', 6),
('mebody_v1_32', 'A6', '②', '상황에 따라 다르거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 1, '밸런스 개선형:Primary', NULL, 6),
('mebody_v1_32', 'A6', '③', '특별한 불안감 없이 자연스럽게 내려간다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 6),
('mebody_v1_32', 'A7', '①', '몸이 뻣뻣해서 원하는 만큼 움직이기 어렵다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 7),
('mebody_v1_32', 'A7', '②', '특별히 불편하거나 이상한 느낌은 없다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 7),
('mebody_v1_32', 'A7', '③', '몸은 잘 움직이지만 힘이 잘 모이지 않거나 자세를 오래 유지하기 어렵다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 1, '밸런스 개선형:Supporting', '유연-불안정 자각', 7),
('mebody_v1_32', 'A8', '①', '거의 매일 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 높음', 8),
('mebody_v1_32', 'A8', '②', '가끔 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 보통', 8),
('mebody_v1_32', 'A8', '③', '거의 하지 않는다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 낮음', 8),
('mebody_v1_32', 'A9', '①', '오른쪽 어깨에서 더 자주 흘러내린다', 'shoulder', 'R', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', '가방 흘러내림', 9),
('mebody_v1_32', 'A9', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 9),
('mebody_v1_32', 'A9', '③', '왼쪽 어깨에서 더 자주 흘러내린다', 'shoulder', 'L', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', '가방 흘러내림', 9),
('mebody_v1_32', 'A10', '①', '팔을 짚어야 하거나 10번 하기 어렵다', NULL, NULL, 0, 'None', NULL, 0, 3, 0, 0, '근력 보완형:Primary', '수행 제한', 10),
('mebody_v1_32', 'A10', '②', '할 수 있지만 뒤로 갈수록 힘들거나 자세가 흐트러진다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 0, '근력 보완형:Primary', '후반 피로', 10),
('mebody_v1_32', 'A10', '③', '비교적 일정하게 10번 할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 10),
('mebody_v1_32', 'B1', '①', '오른쪽 어깨가 더 높다', 'shoulder', 'R', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B1', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B1', '③', '왼쪽 어깨가 더 높다', 'shoulder', 'L', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B2', '①', '왼쪽 골반이 더 앞으로 보인다', 'pelvis', 'R', 4, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B2', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B2', '③', '오른쪽 골반이 더 앞으로 보인다', 'pelvis', 'L', 4, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B3', '①', '왼쪽 골반이 더 앞으로 보인다', 'pelvis', 'R', 3, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B3', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B3', '③', '오른쪽 골반이 더 앞으로 보인다', 'pelvis', 'L', 3, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B4', '①', '귀가 어깨보다 앞으로 나와 있다', 'neck', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B4', '②', '애매하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B4', '③', '귀와 어깨가 비슷한 선에 있다', 'neck', 'C', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B5', '①', '오른쪽이 더 먼저 또는 높이 올라간다', 'shoulder', 'R', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B5', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B5', '③', '왼쪽이 더 먼저 또는 높이 올라간다', 'shoulder', 'L', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B6', '①', '오른쪽 신발이 더 많이 닳았다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'B6', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'B6', '③', '왼쪽 신발이 더 많이 닳았다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'C1', '①', '오른쪽 어깨가 더 먼저 또는 더 많이 올라간다', 'shoulder', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C1', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C1', '③', '왼쪽 어깨가 더 먼저 또는 더 많이 올라간다', 'shoulder', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C2', '①', '무릎이 벽에 닿기 어렵거나 뒤꿈치가 들린다', 'flexibility', 'S', 2, 'Secondary', 2, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 18),
('mebody_v1_32', 'C2', '②', '닿기는 하지만 뻣뻣하거나 한쪽이 더 어렵다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 18),
('mebody_v1_32', 'C2', '③', '양쪽 모두 비교적 편하게 닿는다', 'flexibility', 'F', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 18),
('mebody_v1_32', 'C3', '①', '발을 자주 내리거나 크게 움직여야 한다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 3, '근력 보완형:Secondary / 밸런스 개선형:Primary', '균형 수행 제한', 19),
('mebody_v1_32', 'C3', '②', '유지할 수 있지만 몸이 많이 흔들린다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 1, '밸런스 개선형:Primary', '흔들림', 19),
('mebody_v1_32', 'C3', '③', '비교적 안정적으로 유지할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 19),
('mebody_v1_32', 'C4', '①', '엉덩이보다 허리가 먼저 굽거나 뒤허벅지가 많이 당긴다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 0, 1, '밸런스 개선형:Secondary', NULL, 20),
('mebody_v1_32', 'C4', '②', '허리와 엉덩이가 함께 움직여 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 20),
('mebody_v1_32', 'C4', '③', '엉덩이가 자연스럽게 접히면서 숙여진다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 20),
('mebody_v1_32', 'C5', '①', '손이 무릎 아래로 잘 내려가지 않거나 많이 당긴다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 21),
('mebody_v1_32', 'C5', '②', '손이 정강이 또는 발목 정도까지 내려간다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 21),
('mebody_v1_32', 'C5', '③', '손이 바닥 가까이 비교적 편하게 내려간다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 21),
('mebody_v1_32', 'C6', '①', '귀가 어깨보다 앞으로 나와 있다', 'neck', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C6', '②', '애매하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C6', '③', '귀와 어깨가 비슷한 선에 있다', 'neck', 'C', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C7', '①', '10초 유지하기 어렵다', 'neck', 'F', 2, 'Secondary', 2, 0, 0, 1, 0, '움직임 제한형:Secondary', NULL, 23),
('mebody_v1_32', 'C7', '②', '10초는 가능하지만 불편하거나 힘이 많이 들어간다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목 중심 자세 불편감', 23),
('mebody_v1_32', 'C7', '③', '큰 불편 없이 편하게 10초 유지할 수 있다', 'neck', 'C', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 23),
('mebody_v1_32', 'C8', '①', '오른쪽으로 돌리는 것이 더 편하다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C8', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C8', '③', '왼쪽으로 돌리는 것이 더 편하다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C9', '①', '오른쪽 엉덩이에 더 많이 실린다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'C9', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'C9', '③', '왼쪽 엉덩이에 더 많이 실린다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'D1', '①', '목이 불편해서 바로 베개를 베고 싶다', 'neck', 'F', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D1', '②', '잘 모르겠거나 약간 어색하지만 유지할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D1', '③', '베개 없이도 비교적 편하다', 'neck', 'C', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D2', '①', '허리 아래 공간이 비교적 크다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 27),
('mebody_v1_32', 'D2', '②', '잘 모르겠거나 중간 정도이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 27),
('mebody_v1_32', 'D2', '③', '허리가 바닥에 비교적 가깝다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 27),
('mebody_v1_32', 'D3', '①', '오른발이 더 바깥쪽으로 벌어진다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D3', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D3', '③', '왼발이 더 바깥쪽으로 벌어진다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D4', '①', '오른쪽 무릎이 덜 내려가거나 더 뻣뻣하다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 1, '밸런스 개선형:Supporting', NULL, 29),
('mebody_v1_32', 'D4', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 29),
('mebody_v1_32', 'D4', '③', '왼쪽 무릎이 덜 내려가거나 더 뻣뻣하다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 1, '밸런스 개선형:Supporting', NULL, 29),
('mebody_v1_32', 'D5', '①', '양쪽 모두 잘 올라오지 않거나 많이 뻣뻣하다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 30),
('mebody_v1_32', 'D5', '②', '한쪽만 더 뻣뻣하거나 양쪽 차이가 느껴진다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '고관절 굴곡 좌우 차이', 30),
('mebody_v1_32', 'D5', '③', '양쪽 모두 비교적 편하게 올라온다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 30),
('mebody_v1_32', 'D6', '①', '오른쪽 무릎이 더 편하게 올라온다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D6', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D6', '③', '왼쪽 무릎이 더 편하게 올라온다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D7', '①', '무릎을 굽히지 않으면 허리를 세우기 어렵다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 32),
('mebody_v1_32', 'D7', '②', '앉을 수 있지만 뒤허벅지가 많이 당긴다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 32),
('mebody_v1_32', 'D7', '③', '다리를 편 상태에서도 비교적 편하게 허리를 세울 수 있다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 32)
ON CONFLICT (question_set, question_code, choice) DO UPDATE SET
  choice_summary = EXCLUDED.choice_summary,
  axis = EXCLUDED.axis,
  direction = EXCLUDED.direction,
  axis_weight = EXCLUDED.axis_weight,
  axis_anchor = EXCLUDED.axis_anchor,
  axis_priority = EXCLUDED.axis_priority,
  score_recovery = EXCLUDED.score_recovery,
  score_strength = EXCLUDED.score_strength,
  score_mobility = EXCLUDED.score_mobility,
  score_balance = EXCLUDED.score_balance,
  identity_anchor = EXCLUDED.identity_anchor,
  aux_tag = EXCLUDED.aux_tag,
  display_order = EXCLUDED.display_order,
  updated_at = now();
