UPDATE public.questions
SET is_active = false, updated_at = now()
WHERE COALESCE(question_set, 'v3_full') <> 'sample_subjective_v1'
  AND COALESCE(question_set, 'v3_full') <> 'mebody_v1_32';

DELETE FROM public.questions WHERE question_set = 'mebody_v1_32';
DELETE FROM public.question_choice_scores WHERE question_set = 'mebody_v1_32';

INSERT INTO public.questions (
  question_code, question_number, sort_order, axis,
  question_text, option_1, option_2, option_3,
  weight_a, weight_b, question_version, is_precheck, is_scored, is_active,
  answer_type, max_select, title, part, instruction, guide_text,
  axis_anchor, axis_priority, question_set
) VALUES
('A1', 1, 1, 'none', '최근 규칙적으로 운동하고 있나요?', '일주일에 3회 이상 한다', '일주일에 1~2회 정도 한다', '거의 하지 않는다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '운동 빈도', 'A', '최근 3개월을 기준으로 답합니다.', '[보조] 최근 반복적인 운동 자극을 받고 있는지 확인합니다. 운동 빈도만으로 근력을 판단하지 않으며 A10의 실제 기능 수행과 함께 해석합니다.', 'None', NULL, 'mebody_v1_32'),
('A2', 2, 2, 'none', '충분히 잤다고 느껴도 몸이 개운하지 않은 날이 자주 있나요?', '자주 그렇다', '가끔 그렇다', '거의 그렇지 않다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '수면 후 회복감', 'A', '최근 한 달의 평소 상태를 기준으로 답합니다.', '[핵심] 질환이나 수면장애를 판단하는 문항이 아니라, 사용자가 느끼는 수면 후 회복감을 확인합니다. 생활 리듬·업무량·스트레스의 영향을 함께 고려합니다.', 'None', NULL, 'mebody_v1_32'),
('A3', 3, 3, 'flexibility', '오래 앉아 있다가 일어날 때 몸은 어떤가요?', '몸이 무겁고 뻣뻣해서 바로 움직이기 어렵다', '상황에 따라 다르다', '비교적 바로 편하게 움직일 수 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '오래 앉은 뒤 움직임', 'A', '최근 한 달 동안 오래 앉아 있다가 처음 일어설 때의 경험을 기준으로 답합니다.', '[보조] 오래 앉은 뒤 몸이 다시 움직일 준비를 하는 속도와 뻣뻣함을 함께 확인합니다. 환경 영향을 받으므로 단독 판정에는 사용하지 않습니다.', 'Supporting', 3, 'mebody_v1_32'),
('A4', 4, 4, 'none', '평소보다 많이 움직인 다음 날 몸은 어떤가요?', '다음 날까지 몸이 무겁고 피로가 오래간다', '활동량이나 상황에 따라 다르다', '비교적 잘 회복되는 편이다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '활동 후 회복', 'A', '최근 한 달 동안 오래 걷거나 운동한 다음 날의 경험을 기준으로 답합니다.', '[핵심] 일상 활동 뒤 회복 속도를 직접 확인합니다. 활동량·수면·업무량에 따라 달라질 수 있으므로 A2·A5와 함께 해석합니다.', 'None', NULL, 'mebody_v1_32'),
('A5', 5, 5, 'none', '바쁘거나 긴장되는 일이 끝난 뒤에도 몸의 힘이 쉽게 풀리지 않는 편인가요?', '몸의 긴장이 오래 남는 편이다', '상황에 따라 다르다', '비교적 쉽게 편안해지는 편이다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '긴장 후 이완', 'A', '최근 한 달의 평소 상태를 기준으로 답합니다.', '[핵심] 자율신경 질환을 판단하지 않고, 긴장 상황이 끝난 뒤 주관적으로 편안한 상태로 전환되는 경험을 확인합니다.', 'None', NULL, 'mebody_v1_32'),
('A6', 6, 6, 'none', '계단을 내려갈 때 어떤가요?', '손잡이를 자주 잡거나 불안해서 조심스럽게 내려간다', '상황에 따라 다르거나 잘 모르겠다', '특별한 불안감 없이 자연스럽게 내려간다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '계단 내려가기', 'A', '평소 계단을 내려갈 때의 경험을 기준으로 답합니다. 일부러 계단에서 검사하지 않아도 됩니다.', '[핵심] 계단 하강에서 체중을 받아내는 힘과 중심 조절의 일상적 어려움을 확인합니다.', 'None', NULL, 'mebody_v1_32'),
('A7', 7, 7, 'flexibility', '평소 몸을 움직일 때 어떤 느낌이 가장 가까운가요?', '몸이 뻣뻣해서 원하는 만큼 움직이기 어렵다', '특별히 불편하거나 이상한 느낌은 없다', '몸은 잘 움직이지만 힘이 잘 모이지 않거나 자세를 오래 유지하기 어렵다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '전반적인 몸의 느낌', 'A', '평소 전반적인 몸의 느낌을 기준으로 답합니다.', '[보조] 전반적인 특성을 ‘뻣뻣함’과 ‘잘 움직이지만 안정적으로 유지하기 어려움’으로 나눕니다. 실제 동작 문항과 같은 방향일 때 의미가 커집니다.', 'Supporting', 3, 'mebody_v1_32'),
('A8', 8, 8, 'neck', '평소 목이나 어깨가 뻐근해서 자주 주무르거나 스트레칭을 하나요?', '거의 매일 한다', '가끔 한다', '거의 하지 않는다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '목·어깨 피로 경험', 'A', '최근 한 달을 기준으로 답합니다.', '[해설·동점 참고] 업무환경·스트레스·수면의 영향을 많이 받으므로 축과 아이덴티티 점수에는 직접 반영하지 않습니다. 목·어깨 피로 해설과 결과 동점 시 참고 태그로만 사용합니다.', 'Tie tag', 99, 'mebody_v1_32'),
('A9', 9, 9, 'shoulder', '한쪽 어깨에 가방을 메면 어느 쪽에서 더 자주 흘러내리나요?', '오른쪽 어깨에서 더 자주 흘러내린다', '양쪽이 비슷하거나 잘 모르겠다', '왼쪽 어깨에서 더 자주 흘러내린다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '가방 흘러내림', 'A', '평소 비슷한 형태의 가방을 멜 때를 기준으로 답합니다.', '환경 영향이 큰 보조', 'Supporting', 3, 'mebody_v1_32'),
('A10', 10, 10, 'none', '의자에서 10번 연속으로 일어났다가 앉아보세요. 어떤가요?', '팔을 짚어야 하거나 10번 하기 어렵다', '할 수 있지만 뒤로 갈수록 힘들거나 자세가 흐트러진다', '비교적 일정하게 10번 할 수 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '의자 10회 일어나기', 'A', '팔걸이 없는 안정적인 의자에서 팔을 가슴 앞에 모으고 10회 반복합니다. 통증·어지럼이 생기면 즉시 중단합니다.', '[핵심] 하체 근력, 근지구력, 체간 유지 능력이 함께 필요한 일상 기능 문항입니다. 통증 때문에 수행하지 못한 경우 점수 대신 중단 태그를 기록합니다.', 'None', NULL, 'mebody_v1_32'),
('B1', 11, 11, 'shoulder', '편하게 섰을 때 어느 쪽 어깨가 더 높아 보이나요?', '오른쪽 어깨가 더 높다', '비슷하거나 잘 모르겠다', '왼쪽 어깨가 더 높다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '어깨 높이', 'B', '정면 거울이나 사진에서 양팔과 어깨 힘을 빼고 평소 자세 그대로 확인합니다.', '[핵심 앵커] 정적 선 자세의 어깨 높이 방향을 확인하는 2축 핵심 앵커입니다.', 'Primary', 1, 'mebody_v1_32'),
('B2', 12, 12, 'pelvis', '편하게 섰을 때 어느 쪽 골반 앞부분이 더 앞으로 나와 보이나요?', '왼쪽 골반이 더 앞으로 보인다', '비슷하거나 잘 모르겠다', '오른쪽 골반이 더 앞으로 보인다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '편안한 골반 방향', 'B', '양손 검지를 좌우 골반 앞쪽 돌출부에 가볍게 대거나 정면 사진으로 비교합니다.', '[핵심 앵커] 편안한 선 자세에서 골반 앞부분의 좌우 앞뒤 차이를 확인합니다. 왼쪽이 앞으로 보이면 3축 R, 오른쪽이 앞으로 보이면 3축 L로 계산합니다.', 'Primary', 1, 'mebody_v1_32'),
('B3', 13, 13, 'pelvis', '양쪽 발끝을 정면으로 맞추고 섰을 때 골반 방향은 어떤가요?', '왼쪽 골반이 더 앞으로 보인다', '비슷하거나 잘 모르겠다', '오른쪽 골반이 더 앞으로 보인다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '발 정렬 후 골반 방향', 'B', '발을 어깨너비로 두고 발끝을 11자로 맞춘 뒤 B2와 같은 방법으로 확인합니다.', '[앵커 보조] 발 방향의 영향을 줄인 상태에서도 골반 방향이 유지되는지 확인합니다.', 'Secondary', 2, 'mebody_v1_32'),
('B4', 14, 14, 'neck', '옆모습에서 귀는 어깨보다 앞으로 나와 있나요?', '귀가 어깨보다 앞으로 나와 있다', '애매하거나 잘 모르겠다', '귀와 어깨가 비슷한 선에 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '선 자세 귀 위치', 'B', '옆에서 평소 자세를 촬영하거나 거울로 확인합니다. 턱과 가슴을 일부러 고치지 않습니다.', '[핵심 앵커] 평소 머리를 몸통보다 앞에서 사용하는 경향을 확인합니다. 서기와 앉기 결과가 같으면 1축 확신도가 높아집니다.', 'Primary', 1, 'mebody_v1_32'),
('B5', 15, 15, 'shoulder', '어깨를 천천히 으쓱 올렸을 때 어느 쪽이 먼저 또는 더 높이 올라가나요?', '오른쪽이 더 먼저 또는 높이 올라간다', '비슷하거나 잘 모르겠다', '왼쪽이 더 먼저 또는 높이 올라간다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '어깨 으쓱 비대칭', 'B', '양팔은 몸 옆에 편하게 두고 통증 없는 범위에서 양쪽 어깨를 천천히 으쓱합니다.', '기능 앵커', 'Primary', 1, 'mebody_v1_32'),
('B6', 16, 16, 'pelvis', '자주 신는 신발은 어느 쪽이 더 많이 닳았나요?', '오른쪽 신발이 더 많이 닳았다', '비슷하거나 잘 모르겠다', '왼쪽 신발이 더 많이 닳았다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '신발 밑창 마모', 'B', '최근 자주 신은 비슷한 종류의 신발 밑창을 좌우 비교합니다.', '[저가중치 보조] 보행과 서기에서 반복되는 좌우 체중 사용의 누적 흔적입니다. 신발 종류의 영향을 받아 보조로만 사용합니다.', 'Supporting', 3, 'mebody_v1_32'),
('C1', 17, 17, 'shoulder', '양팔을 앞에서 위로 천천히 올릴 때 어느 쪽 어깨가 귀 쪽으로 더 먼저 올라가나요?', '오른쪽 어깨가 더 먼저 또는 더 많이 올라간다', '양쪽이 비슷하거나 잘 모르겠다', '왼쪽 어깨가 더 먼저 또는 더 많이 올라간다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '팔 올림 시 어깨 상승', 'C', '정면을 보고 서서 양팔을 앞으로 천천히 올립니다. 통증 없는 범위에서 확인합니다.', '[기능 보조] 팔을 올리는 동안 어느 쪽 견갑대가 먼저 상승하는지 확인합니다. B5와 다른 동작에서 2축을 교차 확인합니다.', 'Secondary', 2, 'mebody_v1_32'),
('C2', 18, 18, 'flexibility', '발을 벽에서 약 10cm 떨어뜨리고 무릎을 벽 쪽으로 움직여보세요.', '무릎이 벽에 닿기 어렵거나 뒤꿈치가 들린다', '닿기는 하지만 뻣뻣하거나 한쪽이 더 어렵다', '양쪽 모두 비교적 편하게 닿는다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '발목 벽 닿기', 'C', '맨발로 벽을 향해 서서 엄지발가락 끝과 벽 사이를 약 10cm로 맞춥니다. 뒤꿈치를 바닥에 붙인 채 무릎을 두 번째 발가락 방향으로 벽에 닿도록 움직이고 양쪽을 각각 확인합니다. 통증이 있으면 중단합니다.', '[핵심] 10cm 기준의 무릎-벽 닿기에서 발목 배굴 가동성과 하체가 체중을 받아들이는 움직임 여유를 확인합니다. 발 크기·발 정렬·통증의 영향을 받을 수 있으므로 양쪽 차이와 다른 하체 문항을 함께 해석합니다.', 'Secondary', 2, 'mebody_v1_32'),
('C3', 19, 19, 'none', '한 발로 15초 동안 서보세요. 어떤가요?', '발을 자주 내리거나 크게 움직여야 한다', '유지할 수 있지만 몸이 많이 흔들린다', '비교적 안정적으로 유지할 수 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '한발 서기', 'C', '벽 가까이에서 맨발로 한쪽씩 시행합니다. 넘어질 위험이 있으면 즉시 발을 내립니다.', '[핵심] 발부터 체간까지 한쪽 지지 상태에서의 협응과 균형을 확인합니다.', 'None', NULL, 'mebody_v1_32'),
('C4', 20, 20, 'flexibility', '엉덩이를 뒤로 보내면서 상체를 숙여보세요.', '엉덩이보다 허리가 먼저 굽거나 뒤허벅지가 많이 당긴다', '허리와 엉덩이가 함께 움직여 잘 모르겠다', '엉덩이가 자연스럽게 접히면서 숙여진다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '힙힌지', 'C', '무릎은 살짝 풀고 엉덩이를 뒤로 보내며 상체를 숙입니다. 통증 없는 범위에서 시행합니다.', '[핵심 앵커] 고관절을 사용해 몸을 접는 능력과 허리·골반·고관절의 협응을 확인합니다.', 'Primary', 1, 'mebody_v1_32'),
('C5', 21, 21, 'flexibility', '무릎을 편 상태에서 천천히 상체를 숙여보세요.', '손이 무릎 아래로 잘 내려가지 않거나 많이 당긴다', '손이 정강이 또는 발목 정도까지 내려간다', '손이 바닥 가까이 비교적 편하게 내려간다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '서서 전굴', 'C', '양발을 편하게 두고 반동 없이 천천히 숙입니다. 통증이나 어지럼이 생기면 중단합니다.', '[핵심] 뒤허벅지·종아리·골반·허리 움직임이 결합된 후방사슬의 유연성 경향을 확인합니다.', 'Primary', 1, 'mebody_v1_32'),
('C6', 22, 22, 'neck', '의자에 편하게 앉았을 때 귀 위치는 어떤가요?', '귀가 어깨보다 앞으로 나와 있다', '애매하거나 잘 모르겠다', '귀와 어깨가 비슷한 선에 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '앉은 자세 귀 위치', 'C', '엉덩이를 의자에 편하게 두고 평소 앉는 자세를 옆에서 확인합니다.', '[앵커] 좌식 환경에서 나타나는 머리 위치를 확인합니다. B4와 같은 방향이면 지속 패턴으로 해석합니다.', 'Primary', 1, 'mebody_v1_32'),
('C7', 23, 23, 'neck', '턱을 살짝 뒤로 당긴 상태를 10초 동안 유지해보세요.', '10초 유지하기 어렵다', '10초는 가능하지만 불편하거나 힘이 많이 들어간다', '큰 불편 없이 편하게 10초 유지할 수 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '턱 당기기 유지', 'C', '목을 뒤로 젖히지 말고 턱만 가볍게 뒤로 당깁니다. 통증·어지럼이 생기면 즉시 중단합니다.', '[기능 보조] 머리를 중심 위치로 가져오고 유지하는 능력을 확인합니다. ②는 방향 점수 없이 불편감 태그로 저장합니다.', 'Secondary', 2, 'mebody_v1_32'),
('C8', 24, 24, 'pelvis', '앉아서 상체를 천천히 돌릴 때 어느 쪽이 더 편한가요?', '오른쪽으로 돌리는 것이 더 편하다', '비슷하거나 잘 모르겠다', '왼쪽으로 돌리는 것이 더 편하다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '앉은 몸통 회전', 'C', '양발을 바닥에 두고 골반이 크게 움직이지 않도록 한 뒤 좌우로 천천히 돌립니다.', '몸통 회전 기능', 'Secondary', 2, 'mebody_v1_32'),
('C9', 25, 25, 'pelvis', '의자에 편하게 앉았을 때 어느 쪽 엉덩이에 체중이 더 실리나요?', '오른쪽 엉덩이에 더 많이 실린다', '비슷하거나 잘 모르겠다', '왼쪽 엉덩이에 더 많이 실린다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '앉은 체중 편향', 'C', '평소처럼 20~30초 앉은 뒤 양쪽 엉덩이 아래 압력 차이를 느껴봅니다.', '[기능 보조] 앉은 자세의 좌우 체중 편향을 확인합니다. 다른 골반 문항과 같은 방향일 때 축 결과를 강화합니다.', 'Secondary', 2, 'mebody_v1_32'),
('D1', 26, 26, 'neck', '베개 없이 바로 누우면 어떤 느낌이 가장 가까운가요?', '목이 불편해서 바로 베개를 베고 싶다', '잘 모르겠거나 약간 어색하지만 유지할 수 있다', '베개 없이도 비교적 편하다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '바로 누운 베개 필요감', 'D', '단단하고 평평한 곳에 바로 누워 평소처럼 힘을 뺍니다.', '[기능 보조] 목 정렬뿐 아니라 흉추 형태·어깨 두께·평소 베개 습관의 영향도 받으므로 다른 목 문항과 함께 해석합니다.', 'Supporting', 3, 'mebody_v1_32'),
('D2', 27, 27, 'flexibility', '편하게 누웠을 때 허리와 바닥 사이 공간은 어떤가요?', '허리 아래 공간이 비교적 크다', '잘 모르겠거나 중간 정도이다', '허리가 바닥에 비교적 가깝다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '누운 허리 공간', 'D', '바로 누워 힘을 빼고 손을 허리 아래에 가볍게 넣어 공간을 느껴봅니다.', '[저가중치 보조] 누운 자세에서 허리와 골반이 쉬고 있는 전체 패턴입니다. 다양한 영향을 받아 보조점수로만 사용합니다.', 'Supporting', 3, 'mebody_v1_32'),
('D3', 28, 28, 'pelvis', '편하게 누웠을 때 어느 발이 더 바깥쪽으로 벌어지나요?', '오른발이 더 바깥쪽으로 벌어진다', '비슷하거나 잘 모르겠다', '왼발이 더 바깥쪽으로 벌어진다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '누운 발 벌어짐', 'D', '바로 누워 다리 힘을 빼고 발끝 방향을 좌우 비교합니다.', '[저가중치 보조] 누운 상태에서 다리가 어느 방향으로 더 편하게 놓이는지 확인합니다. 복합 영향을 받아 보조로만 사용합니다.', 'Supporting', 3, 'mebody_v1_32'),
('D4', 29, 29, 'pelvis', '양쪽 무릎을 세운 뒤, 무릎을 한쪽씩 안쪽으로 내려보세요. 어느 쪽이 더 뻣뻣한가요?', '오른쪽 무릎이 덜 내려가거나 더 뻣뻣하다', '양쪽이 비슷하거나 잘 모르겠다', '왼쪽 무릎이 덜 내려가거나 더 뻣뻣하다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '고관절 안쪽 내리기', 'D', '양발을 바닥에 두고 무릎을 세운 뒤 한쪽 무릎씩 몸 안쪽으로 천천히 내려봅니다.', '[기능 보조] 고관절 회전과 골반·허리의 동반 움직임에서 나타나는 좌우 차이를 확인합니다.', 'Secondary', 2, 'mebody_v1_32'),
('D5', 30, 30, 'flexibility', '누워서 왼쪽과 오른쪽 무릎을 한쪽씩 가슴 쪽으로 당겨보세요. 전체적으로 어떤가요?', '양쪽 모두 잘 올라오지 않거나 많이 뻣뻣하다', '한쪽만 더 뻣뻣하거나 양쪽 차이가 느껴진다', '양쪽 모두 비교적 편하게 올라온다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '무릎 가슴 당기기 전체', 'D', '바로 누워 한쪽 무릎씩 천천히 가슴 쪽으로 당깁니다. 양쪽을 같은 방식으로 확인합니다.', '[저가중치 보조] 양쪽 고관절 굴곡의 전체적인 여유를 확인합니다. 한쪽만 제한되면 축 점수는 0점으로 두고 D6에서 좌우 차이를 기록합니다.', 'Supporting', 3, 'mebody_v1_32'),
('D6', 31, 31, 'pelvis', '같은 동작에서 어느 쪽 무릎이 가슴 쪽으로 더 편하게 올라오나요?', '오른쪽 무릎이 더 편하게 올라온다', '양쪽이 비슷하거나 잘 모르겠다', '왼쪽 무릎이 더 편하게 올라온다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '무릎 가슴 당기기 좌우', 'D', 'D5와 같은 자세에서 추가 동작 없이 좌우 차이만 비교합니다.', '좌우 고관절 굴곡의 상대적 차이를 확인합니다. 여러 구조의 영향을 받으므로 저가중치 보조로 사용하며 파일럿 결과에 따라 태그 전용으로 전환할 수 있습니다.', 'Supporting', 3, 'mebody_v1_32'),
('D7', 32, 32, 'flexibility', '다리를 앞으로 펴고 바닥에 앉았을 때 어떤가요?', '무릎을 굽히지 않으면 허리를 세우기 어렵다', '앉을 수 있지만 뒤허벅지가 많이 당긴다', '다리를 편 상태에서도 비교적 편하게 허리를 세울 수 있다', 0, 0, 'mebody_v1_32', false, true, true, 'single', NULL, '장좌 자세', 'D', '누운 검사 종료 후 한 번만 일어나 양다리를 편 상태로 앉아 허리를 편하게 세워봅니다. 통증이나 저림이 생기면 중단합니다.', '햄스트링 유연성, 골반 움직임, 앉은 자세에서 허리를 세우는 능력을 함께 확인합니다. 바닥 파트의 마지막에 배치해 자세 전환을 한 번으로 줄입니다.', 'Primary', 1, 'mebody_v1_32')
ON CONFLICT (question_code, question_set) DO UPDATE SET
  question_number = EXCLUDED.question_number,
  sort_order = EXCLUDED.sort_order,
  axis = EXCLUDED.axis,
  question_text = EXCLUDED.question_text,
  option_1 = EXCLUDED.option_1,
  option_2 = EXCLUDED.option_2,
  option_3 = EXCLUDED.option_3,
  title = EXCLUDED.title,
  part = EXCLUDED.part,
  instruction = EXCLUDED.instruction,
  guide_text = EXCLUDED.guide_text,
  axis_anchor = EXCLUDED.axis_anchor,
  axis_priority = EXCLUDED.axis_priority,
  is_active = true,
  question_version = 'mebody_v1_32',
  updated_at = now();

INSERT INTO public.question_choice_scores (
  question_set, question_code, choice, choice_summary,
  axis, direction, axis_weight, axis_anchor, axis_priority,
  score_recovery, score_strength, score_mobility, score_balance,
  identity_anchor, aux_tag, display_order
) VALUES
('mebody_v1_32', 'A1', '①', '일주일에 3회 이상 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 1),
('mebody_v1_32', 'A1', '②', '일주일에 1~2회 정도 한다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 0, '근력 보완형:Supporting', NULL, 1),
('mebody_v1_32', 'A1', '③', '거의 하지 않는다', NULL, NULL, 0, 'None', NULL, 0, 2, 0, 0, '근력 보완형:Supporting', NULL, 1),
('mebody_v1_32', 'A2', '①', '자주 그렇다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '수면 후 회복감 낮음', 2),
('mebody_v1_32', 'A2', '②', '가끔 그렇다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', '수면 후 회복감 변동', 2),
('mebody_v1_32', 'A2', '③', '거의 그렇지 않다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 2),
('mebody_v1_32', 'A3', '①', '몸이 무겁고 뻣뻣해서 바로 움직이기 어렵다', 'flexibility', 'S', 1, 'Supporting', 3, 2, 0, 1, 0, '회복 우선형:Supporting / 움직임 제한형:Supporting', NULL, 3),
('mebody_v1_32', 'A3', '②', '상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Supporting', NULL, 3),
('mebody_v1_32', 'A3', '③', '비교적 바로 편하게 움직일 수 있다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 3),
('mebody_v1_32', 'A4', '①', '다음 날까지 몸이 무겁고 피로가 오래간다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '활동 후 회복 지연', 4),
('mebody_v1_32', 'A4', '②', '활동량이나 상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', NULL, 4),
('mebody_v1_32', 'A4', '③', '비교적 잘 회복되는 편이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 4),
('mebody_v1_32', 'A5', '①', '몸의 긴장이 오래 남는 편이다', NULL, NULL, 0, 'None', NULL, 3, 0, 0, 0, '회복 우선형:Primary', '긴장 후 이완 지연', 5),
('mebody_v1_32', 'A5', '②', '상황에 따라 다르다', NULL, NULL, 0, 'None', NULL, 1, 0, 0, 0, '회복 우선형:Primary', NULL, 5),
('mebody_v1_32', 'A5', '③', '비교적 쉽게 편안해지는 편이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 5),
('mebody_v1_32', 'A6', '①', '손잡이를 자주 잡거나 불안해서 조심스럽게 내려간다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 3, '근력 보완형:Secondary / 밸런스 개선형:Primary', '계단 불안/손잡이', 6),
('mebody_v1_32', 'A6', '②', '상황에 따라 다르거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 1, '밸런스 개선형:Primary', NULL, 6),
('mebody_v1_32', 'A6', '③', '특별한 불안감 없이 자연스럽게 내려간다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 6),
('mebody_v1_32', 'A7', '①', '몸이 뻣뻣해서 원하는 만큼 움직이기 어렵다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 7),
('mebody_v1_32', 'A7', '②', '특별히 불편하거나 이상한 느낌은 없다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 7),
('mebody_v1_32', 'A7', '③', '몸은 잘 움직이지만 힘이 잘 모이지 않거나 자세를 오래 유지하기 어렵다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 1, '밸런스 개선형:Supporting', '유연-불안정 자각', 7),
('mebody_v1_32', 'A8', '①', '거의 매일 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 높음', 8),
('mebody_v1_32', 'A8', '②', '가끔 한다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 보통', 8),
('mebody_v1_32', 'A8', '③', '거의 하지 않는다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목·어깨 피로 낮음', 8),
('mebody_v1_32', 'A9', '①', '오른쪽 어깨에서 더 자주 흘러내린다', 'shoulder', 'R', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', '가방 흘러내림', 9),
('mebody_v1_32', 'A9', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 9),
('mebody_v1_32', 'A9', '③', '왼쪽 어깨에서 더 자주 흘러내린다', 'shoulder', 'L', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', '가방 흘러내림', 9),
('mebody_v1_32', 'A10', '①', '팔을 짚어야 하거나 10번 하기 어렵다', NULL, NULL, 0, 'None', NULL, 0, 3, 0, 0, '근력 보완형:Primary', '수행 제한', 10),
('mebody_v1_32', 'A10', '②', '할 수 있지만 뒤로 갈수록 힘들거나 자세가 흐트러진다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 0, '근력 보완형:Primary', '후반 피로', 10),
('mebody_v1_32', 'A10', '③', '비교적 일정하게 10번 할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 10),
('mebody_v1_32', 'B1', '①', '오른쪽 어깨가 더 높다', 'shoulder', 'R', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B1', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B1', '③', '왼쪽 어깨가 더 높다', 'shoulder', 'L', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 11),
('mebody_v1_32', 'B2', '①', '왼쪽 골반이 더 앞으로 보인다', 'pelvis', 'R', 4, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B2', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B2', '③', '오른쪽 골반이 더 앞으로 보인다', 'pelvis', 'L', 4, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 12),
('mebody_v1_32', 'B3', '①', '왼쪽 골반이 더 앞으로 보인다', 'pelvis', 'R', 3, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B3', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B3', '③', '오른쪽 골반이 더 앞으로 보인다', 'pelvis', 'L', 3, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 13),
('mebody_v1_32', 'B4', '①', '귀가 어깨보다 앞으로 나와 있다', 'neck', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B4', '②', '애매하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B4', '③', '귀와 어깨가 비슷한 선에 있다', 'neck', 'C', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 14),
('mebody_v1_32', 'B5', '①', '오른쪽이 더 먼저 또는 높이 올라간다', 'shoulder', 'R', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B5', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B5', '③', '왼쪽이 더 먼저 또는 높이 올라간다', 'shoulder', 'L', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 15),
('mebody_v1_32', 'B6', '①', '오른쪽 신발이 더 많이 닳았다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'B6', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'B6', '③', '왼쪽 신발이 더 많이 닳았다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 16),
('mebody_v1_32', 'C1', '①', '오른쪽 어깨가 더 먼저 또는 더 많이 올라간다', 'shoulder', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C1', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C1', '③', '왼쪽 어깨가 더 먼저 또는 더 많이 올라간다', 'shoulder', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 17),
('mebody_v1_32', 'C2', '①', '무릎이 벽에 닿기 어렵거나 뒤꿈치가 들린다', 'flexibility', 'S', 2, 'Secondary', 2, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 18),
('mebody_v1_32', 'C2', '②', '닿기는 하지만 뻣뻣하거나 한쪽이 더 어렵다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 18),
('mebody_v1_32', 'C2', '③', '양쪽 모두 비교적 편하게 닿는다', 'flexibility', 'F', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 18),
('mebody_v1_32', 'C3', '①', '발을 자주 내리거나 크게 움직여야 한다', NULL, NULL, 0, 'None', NULL, 0, 1, 0, 3, '근력 보완형:Secondary / 밸런스 개선형:Primary', '균형 수행 제한', 19),
('mebody_v1_32', 'C3', '②', '유지할 수 있지만 몸이 많이 흔들린다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 1, '밸런스 개선형:Primary', '흔들림', 19),
('mebody_v1_32', 'C3', '③', '비교적 안정적으로 유지할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 19),
('mebody_v1_32', 'C4', '①', '엉덩이보다 허리가 먼저 굽거나 뒤허벅지가 많이 당긴다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 0, 1, '밸런스 개선형:Secondary', NULL, 20),
('mebody_v1_32', 'C4', '②', '허리와 엉덩이가 함께 움직여 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 20),
('mebody_v1_32', 'C4', '③', '엉덩이가 자연스럽게 접히면서 숙여진다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 20),
('mebody_v1_32', 'C5', '①', '손이 무릎 아래로 잘 내려가지 않거나 많이 당긴다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 21),
('mebody_v1_32', 'C5', '②', '손이 정강이 또는 발목 정도까지 내려간다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 21),
('mebody_v1_32', 'C5', '③', '손이 바닥 가까이 비교적 편하게 내려간다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 21),
('mebody_v1_32', 'C6', '①', '귀가 어깨보다 앞으로 나와 있다', 'neck', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C6', '②', '애매하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C6', '③', '귀와 어깨가 비슷한 선에 있다', 'neck', 'C', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 22),
('mebody_v1_32', 'C7', '①', '10초 유지하기 어렵다', 'neck', 'F', 2, 'Secondary', 2, 0, 0, 1, 0, '움직임 제한형:Secondary', NULL, 23),
('mebody_v1_32', 'C7', '②', '10초는 가능하지만 불편하거나 힘이 많이 들어간다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '목 중심 자세 불편감', 23),
('mebody_v1_32', 'C7', '③', '큰 불편 없이 편하게 10초 유지할 수 있다', 'neck', 'C', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 23),
('mebody_v1_32', 'C8', '①', '오른쪽으로 돌리는 것이 더 편하다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C8', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C8', '③', '왼쪽으로 돌리는 것이 더 편하다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 24),
('mebody_v1_32', 'C9', '①', '오른쪽 엉덩이에 더 많이 실린다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'C9', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'C9', '③', '왼쪽 엉덩이에 더 많이 실린다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 0, 'None', NULL, 25),
('mebody_v1_32', 'D1', '①', '목이 불편해서 바로 베개를 베고 싶다', 'neck', 'F', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D1', '②', '잘 모르겠거나 약간 어색하지만 유지할 수 있다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D1', '③', '베개 없이도 비교적 편하다', 'neck', 'C', 2, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 26),
('mebody_v1_32', 'D2', '①', '허리 아래 공간이 비교적 크다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 27),
('mebody_v1_32', 'D2', '②', '잘 모르겠거나 중간 정도이다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 27),
('mebody_v1_32', 'D2', '③', '허리가 바닥에 비교적 가깝다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 27),
('mebody_v1_32', 'D3', '①', '오른발이 더 바깥쪽으로 벌어진다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D3', '②', '비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D3', '③', '왼발이 더 바깥쪽으로 벌어진다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 28),
('mebody_v1_32', 'D4', '①', '오른쪽 무릎이 덜 내려가거나 더 뻣뻣하다', 'pelvis', 'R', 2, 'Secondary', 2, 0, 0, 0, 1, '밸런스 개선형:Supporting', NULL, 29),
('mebody_v1_32', 'D4', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 29),
('mebody_v1_32', 'D4', '③', '왼쪽 무릎이 덜 내려가거나 더 뻣뻣하다', 'pelvis', 'L', 2, 'Secondary', 2, 0, 0, 0, 1, '밸런스 개선형:Supporting', NULL, 29),
('mebody_v1_32', 'D5', '①', '양쪽 모두 잘 올라오지 않거나 많이 뻣뻣하다', 'flexibility', 'S', 1, 'Supporting', 3, 0, 0, 1, 0, '움직임 제한형:Supporting', NULL, 30),
('mebody_v1_32', 'D5', '②', '한쪽만 더 뻣뻣하거나 양쪽 차이가 느껴진다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', '고관절 굴곡 좌우 차이', 30),
('mebody_v1_32', 'D5', '③', '양쪽 모두 비교적 편하게 올라온다', 'flexibility', 'F', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 30),
('mebody_v1_32', 'D6', '①', '오른쪽 무릎이 더 편하게 올라온다', 'pelvis', 'L', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D6', '②', '양쪽이 비슷하거나 잘 모르겠다', NULL, NULL, 0, 'None', NULL, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D6', '③', '왼쪽 무릎이 더 편하게 올라온다', 'pelvis', 'R', 1, 'Supporting', 3, 0, 0, 0, 0, 'None', NULL, 31),
('mebody_v1_32', 'D7', '①', '무릎을 굽히지 않으면 허리를 세우기 어렵다', 'flexibility', 'S', 3, 'Primary', 1, 0, 0, 3, 0, '움직임 제한형:Primary', NULL, 32),
('mebody_v1_32', 'D7', '②', '앉을 수 있지만 뒤허벅지가 많이 당긴다', NULL, NULL, 0, 'None', NULL, 0, 0, 1, 0, '움직임 제한형:Primary', NULL, 32),
('mebody_v1_32', 'D7', '③', '다리를 편 상태에서도 비교적 편하게 허리를 세울 수 있다', 'flexibility', 'F', 3, 'Primary', 1, 0, 0, 0, 0, 'None', NULL, 32)
ON CONFLICT (question_set, question_code, choice) DO UPDATE SET
  choice_summary = EXCLUDED.choice_summary,
  axis = EXCLUDED.axis,
  direction = EXCLUDED.direction,
  axis_weight = EXCLUDED.axis_weight,
  axis_anchor = EXCLUDED.axis_anchor,
  axis_priority = EXCLUDED.axis_priority,
  score_recovery = EXCLUDED.score_recovery,
  score_strength = EXCLUDED.score_strength,
  score_mobility = EXCLUDED.score_mobility,
  score_balance = EXCLUDED.score_balance,
  identity_anchor = EXCLUDED.identity_anchor,
  aux_tag = EXCLUDED.aux_tag,
  display_order = EXCLUDED.display_order,
  updated_at = now();
